xero:
  target: "{{ env_var('DBT_TARGET=xero_ail') }}"
  outputs:
    xero_ail:
      type: sqlserver
      driver: 'ODBC Driver 18 for SQL Server'
      server: "{{ env_var('DBT_SQL_SERVER_NAME ') }}"
      port: 1433
      database: ailsqldev
      schema: dbtXero
      user: "{{ env_var('DBT_SQL_USERNAME') }}"
      password: "{{ env_var('DBT_SQL_PASSWORD') }}"
      retries: 2
      threads: 10

    xero_sl:
      type: sqlserver
      driver: 'ODBC Driver 18 for SQL Server'
      server: "{{ env_var('DBT_SQL_SERVER_NAME ') }}"
      port: 1433
      database: slsqldev
      schema: dbtXero
      user: "{{ env_var('DBT_SQL_USERNAME') }}"
      password: "{{ env_var('DBT_SQL_PASSWORD') }}"
      retries: 2
      threads: 10
