xero:
  target: xero_ail
  outputs:
    xero_ail:
      type: sqlserver
      driver: 'ODBC Driver 18 for SQL Server'
      server: "{{ env_var('vSQL_SERVER_NAME') }}"
      port: 1433
      database: ailsqldev
      schema: xero
      user: "{{ env_var('vSQL_USERNAME') }}"
      password: "{{ env_var('vSQL_PASSWORD') }}"
      retries: 2
      threads: 10

    xero_sl:
      type: sqlserver
      driver: 'ODBC Driver 18 for SQL Server'
      server: "{{ env_var('vSQL_SERVER_NAME') }}"
      port: 1433
      database: slsqldev
      schema: xero
      user: "{{ env_var('vSQL_USERNAME') }}"
      password: "{{ env_var('vSQL_PASSWORD') }}"
      retries: 2
      threads: 10
